apiVersion: apps/v1
kind: Deployment 
metadata:
  name: usermgmt-microservice
  labels:
    app: usermgmt-restapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usermgmt-restapp
  template:  
    metadata:
      labels: 
        app: usermgmt-restapp
    spec:
      containers:
        - name: usermgmt-restapp
          image: stacksimplify/kube-usermanagement-microservice:1.0.0
          ports: 
            - containerPort: 8095           
          env:
            - name: DB_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: usermanagement-dbcreation-script
                  key: db_hostname
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: usermanagement-dbcreation-script
                  key: db_port
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: usermanagement-dbcreation-script
                  key: db_name
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: usermanagement-dbcreation-script
                  key: db_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-db-password
                  key: db-password

                  dbpassword11