apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-mysql-pv-claim
spec: 
  accessModes:
    - ReadWriteOnce # the volume can be mounted as read-write by a single node
  storageClassName: ebs-sc
  resources: 
    requests:
      storage: 4Gi